#!/usr/bin/env python3
"""Write PROJECT/76-BACKFILL.md — the plate ledger for the backfill sweep.

The ledger is never typed by hand.  It runs `tools/img_import.py --check`, reads the
`X of Y notes carry a plate` lines it prints, subtracts the subjects the owner freed
from pictures (see `EXEMPT` — five word-only subjects, in every term), and lays the rest out as a queue
with the term's own line on it.  Run it at the start of a sweep turn and again at the end.
"""
from __future__ import annotations

import argparse
import collections
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
EXEMPT = {"yoruba", "general-knowledge", "nigerian-history",     # owner's word, 2 Sep 2026:
          "social-and-citizenship-studies",                       #   these subjects carry no art
          "christian-religious-studies"}                          #   "CRS does not need images"
TERM_ORDER = {"2nd-term": 0, "1st-term": 1, "3rd-term": 2}
TERM_PRETTY = {"1st-term": "First Term", "2nd-term": "Second Term", "3rd-term": "Third Term"}
LINE = re.compile(r"plates\s+: (\d+(?:st|nd|rd)-term)/([a-z0-9-]+): (\d+) of (\d+) notes carry a plate")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--class", dest="cls", default="Nursery 2")
    a = ap.parse_args()
    out = subprocess.run([sys.executable, str(ROOT / "tools/img_import.py"), "--check"],
                         capture_output=True, text=True, cwd=ROOT)
    if out.returncode not in (0, 1):                 # --check exits non-zero while plates are owed
        sys.exit(out.stdout + out.stderr)
    text = out.stdout + out.stderr
    owed: dict[tuple[str, str], tuple[int, int]] = {}
    exempt: collections.Counter = collections.Counter()
    for m in LINE.finditer(text):
        term, subj, have, want = m.group(1), m.group(2), int(m.group(3)), int(m.group(4))
        if subj in EXEMPT:
            exempt[term] += want - have
            continue
        if want - have > 0:
            owed[(term, subj)] = (have, want)

    rows = []
    by_term: dict[str, list] = collections.defaultdict(list)
    for (term, subj), (have, want) in owed.items():
        by_term[term].append((subj, have, want))
    total = 0
    for term in sorted(by_term, key=lambda t: TERM_ORDER.get(t, 9)):
        for subj, have, want in sorted(by_term[term]):
            gap = want - have
            total += gap
            done = "✅ whole" if gap == 0 else f"**{gap} owed**"
            rows.append(f"| {TERM_PRETTY.get(term, term)} | `{subj}` | {have} of {want} | {done} |")

    lines = [
        "# Backfill ledger — one plate for every note that still has none",
        "",
        f"Generated by `python3 tools/backfill_ledger.py` — do not edit this table by hand, it is",
        "re-derived from `tools/img_import.py --check` each turn.  {n} plate(s) owed.".format(n=total),
        "",
        "| term | subject file | plates in the book | state |",
        "| --- | --- | --- | --- |",
    ] + (rows or ["| — | — | — | nothing owed |"]) + [
        "",
        f"**Exempt, never owed** ({sum(exempt.values())} notes): Yoruba, General Knowledge, Nigerian History,",
        "Social & Citizenship Studies and Christian Religious Studies — *\"Yoruba doesn't need images\"*,",
        "*\"GK does not need images too\"*, *\"Nigerian History and Social and Citizenship Studies need no",
        "images\"* and *\"CRS does not need images\"* (owner, 2 Sep 2026), in **every** term.",
        "`--check` still prints their shortfall lines; they are subtracted here and are never generated.  Plates",
        "already drawn and filed for an exempt subject stay where they are — nothing is stripped out of a book.",
        "",
        "## How a sweep turn runs",
        "",
        "1. Take the top unfinished row and read that file's `### WEEK` heads plus its `**You will learn to**`",
        "   bullets — the plate draws the **scene** the note teaches.",
        "2. Every writing surface in the drawing is blank: no letters, no words, no numbers, no drawn punctuation;",
        "   a clock gets twelve marks and no numerals; a full stop is one small solid round dot.  People are drawn",
        "   whole, head to shoes, one scene per page, nothing cut by the edge, colouring-book line art only.",
        "3. Flatten the turn's raws into one contact sheet at the print threshold, **read it**, delete a reject in",
        "   the same turn and re-make it, never overwrite a good file.",
        "4. `tools/img_import.py` per plate (give `cwd` as a plain path), then rebuild that term's book and run",
        "   `tools/gates.py --class \"Nursery 2\" --term \"<term>\"`; the book line must end `rule checks: all clear`.",
        "5. Ten plates a turn is the ceiling (the generator allows ten generations); a subject is finished before",
        "   the next one starts, so each file's children and props stay consistent.",
        "",
        "First and Second Term books carry the notes and the papers already — only the drawings are missing there,",
        "so nothing is authored in a sweep turn and no paper is re-lettered.",
        "",
    ]
    dest = ROOT / "PROJECT/76-BACKFILL.md"
    dest.write_text("\n".join(lines), encoding="utf-8")
    print(f"ledger    : {dest.relative_to(ROOT)} · {total} plate(s) owed · "
          f"{len(rows)} subject file(s) · exempt notes {sum(exempt.values())}")
    for r in rows:
        print("   ", r)
    return 0


if __name__ == "__main__":
    sys.exit(main())
